[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pphys"
version = "0.0.9"
readme = "README.md"
dependencies = [
    "numpy>=1.26.4",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["pphys*"]
